# Generated by Django 6.0.1 on 2026-01-11 18:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Core",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("type", models.CharField(blank=True, default="", max_length=60)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("Common", "Common"),
                            ("Uncommon", "Uncommon"),
                            ("Rare", "Rare"),
                            ("Legendary", "Legendary"),
                            ("Mythic", "Mythic"),
                        ],
                        default="Common",
                        max_length=20,
                    ),
                ),
                ("lvl", models.PositiveIntegerField(default=0)),
                ("decommed", models.BooleanField(default=False)),
                ("price", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Garage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bay_doors", models.PositiveIntegerField(default=3)),
                ("core_loadouts", models.JSONField(blank=True, default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImageAsset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_id", models.CharField(max_length=128, unique=True)),
                ("main", models.BooleanField(default=False)),
                (
                    "r",
                    models.PositiveIntegerField(
                        default=255,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(255),
                        ],
                    ),
                ),
                (
                    "g",
                    models.PositiveIntegerField(
                        default=255,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(255),
                        ],
                    ),
                ),
                (
                    "b",
                    models.PositiveIntegerField(
                        default=255,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(255),
                        ],
                    ),
                ),
                (
                    "battle_image",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("battle_animation", models.JSONField(blank=True, default=list)),
                ("dmg_animation", models.JSONField(blank=True, default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lvl", models.PositiveIntegerField(default=0)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("loses", models.PositiveIntegerField(default=0)),
                ("bits", models.PositiveIntegerField(default=0)),
                ("premium", models.PositiveIntegerField(default=0)),
                ("zones", models.JSONField(blank=True, default=list)),
                ("choices", models.JSONField(blank=True, default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Scrapyard",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("items_for_sale", models.JSONField(blank=True, default=list)),
                ("bundles", models.JSONField(blank=True, default=list)),
                ("weekly_deal", models.JSONField(blank=True, default=dict)),
                ("purchase_logs", models.JSONField(blank=True, default=list)),
                ("decommed_cores", models.JSONField(blank=True, default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CoreBattleInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hp", models.PositiveIntegerField(default=0)),
                ("physical", models.PositiveIntegerField(default=0)),
                ("energy", models.PositiveIntegerField(default=0)),
                ("defense", models.PositiveIntegerField(default=0)),
                ("shield", models.PositiveIntegerField(default=0)),
                ("speed", models.PositiveIntegerField(default=0)),
                ("equip_slots", models.PositiveIntegerField(default=4)),
                (
                    "core",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_info",
                        to="codex.core",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CoreUpgradeInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exp", models.PositiveIntegerField(default=0)),
                ("next_lvl", models.PositiveIntegerField(default=0)),
                ("upgradeable", models.BooleanField(default=True)),
                ("tracks", models.JSONField(blank=True, default=list)),
                ("lvl_logs", models.JSONField(blank=True, default=list)),
                (
                    "core",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrade_info",
                        to="codex.core",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="core",
            name="garage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cores",
                to="codex.garage",
            ),
        ),
        migrations.AddField(
            model_name="core",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cores",
                to="codex.imageasset",
            ),
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("type", models.CharField(blank=True, default="", max_length=60)),
                (
                    "dmg_type",
                    models.CharField(
                        choices=[
                            ("ENERGY", "Energy Ammo"),
                            ("PHYSICAL", "Physical Ammo"),
                        ],
                        max_length=16,
                    ),
                ),
                ("dmg", models.IntegerField(default=0)),
                (
                    "accuracy",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("resource_cost", models.PositiveIntegerField(default=0)),
                ("lvl_learned", models.PositiveIntegerField(default=0)),
                (
                    "core_type_identity",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("track_type", models.CharField(blank=True, default="", max_length=60)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moves",
                        to="codex.imageasset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("type", models.CharField(blank=True, default="", max_length=60)),
                ("equipped", models.BooleanField(default=False)),
                ("bonuses", models.JSONField(blank=True, default=list)),
                (
                    "buy_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "sell_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "rarity",
                    models.CharField(blank=True, default="Common", max_length=30),
                ),
                ("is_move", models.BooleanField(default=False)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment",
                        to="codex.imageasset",
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="as_equipment",
                        to="codex.move",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CoreEquippedMove",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slot", models.PositiveIntegerField(default=1)),
                (
                    "core",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="codex.core"
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="codex.move"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="core",
            name="equipped_moves",
            field=models.ManyToManyField(
                related_name="equipped_by_cores",
                through="codex.CoreEquippedMove",
                to="codex.move",
            ),
        ),
        migrations.AddField(
            model_name="core",
            name="moves_pool",
            field=models.ManyToManyField(
                blank=True, related_name="cores_with_access", to="codex.move"
            ),
        ),
        migrations.AddField(
            model_name="garage",
            name="operator",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="garage",
                to="codex.operator",
            ),
        ),
        migrations.AddConstraint(
            model_name="coreequippedmove",
            constraint=models.UniqueConstraint(
                fields=("core", "move"), name="uniq_core_move"
            ),
        ),
        migrations.AddConstraint(
            model_name="coreequippedmove",
            constraint=models.UniqueConstraint(
                fields=("core", "slot"), name="uniq_core_slot"
            ),
        ),
    ]
