# Generated by Django 6.0.1 on 2026-01-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="call_sign",
            field=models.CharField(default="000", max_length=120),
        ),
    ]
