# Generated by Django 6.0.1 on 2026-01-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0002_operator_call_sign"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="rank",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "S"),
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                ],
                default="F",
                max_length=60,
            ),
        ),
    ]
