# Generated by Django 6.0.1 on 2026-01-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0003_operator_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="core",
            name="image_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
