# Generated by Django 6.0.1 on 2026-01-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0004_core_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="is_starter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="move",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("Common", "Common"),
                    ("Uncommon", "Uncommon"),
                    ("Rare", "Rare"),
                    ("Legendary", "Legendary"),
                    ("Mythic", "Mythic"),
                ],
                default="Common",
                max_length=20,
            ),
        ),
    ]
