# Generated by Django 5.2.7 on 2026-01-19 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0005_move_is_starter_move_rarity"),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="is_signature",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="move",
            name="core_type_identity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Techno", "Techno"),
                    ("Bio", "Bio"),
                    ("Hybrid", "Hybrid"),
                    ("Quantum", "Quantum"),
                    ("Nano", "Nano"),
                    ("Cyber", "Cyber"),
                    ("Mecha", "Mecha"),
                    ("Plasma", "Plasma"),
                    ("Void", "Void"),
                    ("Solar", "Solar"),
                    ("Arcane", "Arcane"),
                    ("Electric", "Electric"),
                    ("Magnetic", "Magnetic"),
                    ("Gravitic", "Gravitic"),
                    ("Thermal", "Thermal"),
                    ("Acidic", "Acidic"),
                    ("Radiant", "Radiant"),
                    ("Psychic", "Psychic"),
                    ("Nuclear", "Nuclear"),
                    ("Temporal", "Temporal"),
                ],
                default="",
                max_length=60,
            ),
        ),
        migrations.CreateModel(
            name="GarageMoveLibrary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("copies_owned", models.PositiveIntegerField(default=1)),
                (
                    "garage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="codex.garage"
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="codex.move"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="garage",
            name="move_library",
            field=models.ManyToManyField(
                blank=True,
                related_name="garages_owned",
                through="codex.GarageMoveLibrary",
                to="codex.move",
            ),
        ),
        migrations.AddIndex(
            model_name="garagemovelibrary",
            index=models.Index(
                fields=["garage", "move"], name="codex_garag_garage__b18fee_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="garagemovelibrary",
            constraint=models.UniqueConstraint(
                fields=("garage", "move"), name="uniq_garage_move"
            ),
        ),
        migrations.AddConstraint(
            model_name="garagemovelibrary",
            constraint=models.CheckConstraint(
                condition=models.Q(("copies_owned__lte", 2)), name="max_2_copies"
            ),
        ),
    ]
