# battle/constants.py
# Constants for the Battle system

# Battle Types
BATTLE_TYPE_PVP = "PVP"
BATTLE_TYPE_PVE = "PVE"
BATTLE_TYPE_MISSION = "MISSION"

BATTLE_TYPES = [BATTLE_TYPE_PVP, BATTLE_TYPE_PVE, BATTLE_TYPE_MISSION]

# Battle Status
BATTLE_STATUS_PENDING = "PENDING"
BATTLE_STATUS_ACTIVE = "ACTIVE"
BATTLE_STATUS_COMPLETED = "COMPLETED"
BATTLE_STATUS_ABANDONED = "ABANDONED"

BATTLE_STATUSES = [
    BATTLE_STATUS_PENDING,
    BATTLE_STATUS_ACTIVE,
    BATTLE_STATUS_COMPLETED,
    BATTLE_STATUS_ABANDONED,
]

# Action Types
ACTION_TYPE_MOVE = "MOVE"
ACTION_TYPE_SWITCH = "SWITCH"
ACTION_TYPE_PASS = "PASS"
ACTION_TYPE_GAIN_RESOURCE = "GAIN_RESOURCE"
ACTION_TYPE_REACTION = "REACTION"

ACTION_TYPES = [
    ACTION_TYPE_MOVE,
    ACTION_TYPE_SWITCH,
    ACTION_TYPE_PASS,
    ACTION_TYPE_GAIN_RESOURCE,
    ACTION_TYPE_REACTION,
]

# Resource Pool Types
RESOURCE_ENERGY = "ENERGY"
RESOURCE_PHYSICAL = "PHYSICAL"

RESOURCE_TYPES = [RESOURCE_ENERGY, RESOURCE_PHYSICAL]

# Dice Configuration
DICE_MIN = 1
DICE_MAX = 8
DICE_TYPE = "d8"

# Team Configuration
MAX_CORES_PER_TEAM = 3
CORE_POSITIONS = [0, 1, 2]

# Mission Difficulty
DIFFICULTY_EASY = "EASY"
DIFFICULTY_MEDIUM = "MEDIUM"
DIFFICULTY_HARD = "HARD"
DIFFICULTY_EXTREME = "EXTREME"

DIFFICULTIES = [
    DIFFICULTY_EASY,
    DIFFICULTY_MEDIUM,
    DIFFICULTY_HARD,
    DIFFICULTY_EXTREME,
]

# Difficulty multipliers for enemy stat scaling
DIFFICULTY_MULTIPLIERS = {
    DIFFICULTY_EASY: 0.8,
    DIFFICULTY_MEDIUM: 1.0,
    DIFFICULTY_HARD: 1.3,
    DIFFICULTY_EXTREME: 1.6,
}

# Base rewards per difficulty
DIFFICULTY_REWARDS = {
    DIFFICULTY_EASY: {"bits": 50, "exp": 25},
    DIFFICULTY_MEDIUM: {"bits": 100, "exp": 50},
    DIFFICULTY_HARD: {"bits": 200, "exp": 100},
    DIFFICULTY_EXTREME: {"bits": 400, "exp": 200},
}

# Mission Status
MISSION_STATUS_AVAILABLE = "AVAILABLE"
MISSION_STATUS_ACTIVE = "ACTIVE"
MISSION_STATUS_COMPLETED = "COMPLETED"
MISSION_STATUS_FAILED = "FAILED"
MISSION_STATUS_EXPIRED = "EXPIRED"

MISSION_STATUSES = [
    MISSION_STATUS_AVAILABLE,
    MISSION_STATUS_ACTIVE,
    MISSION_STATUS_COMPLETED,
    MISSION_STATUS_FAILED,
    MISSION_STATUS_EXPIRED,
]

# Mail Types
MAIL_TYPE_SYSTEM = "SYSTEM"
MAIL_TYPE_REWARD = "REWARD"
MAIL_TYPE_BATTLE_RESULT = "BATTLE_RESULT"
MAIL_TYPE_MISSION_UPDATE = "MISSION_UPDATE"

MAIL_TYPES = [
    MAIL_TYPE_SYSTEM,
    MAIL_TYPE_REWARD,
    MAIL_TYPE_BATTLE_RESULT,
    MAIL_TYPE_MISSION_UPDATE,
]

# Combat Constants
CRITICAL_HIT_MULTIPLIER = 1.5
BASE_CRITICAL_CHANCE = 0.0625  # 6.25% — matches Pokémon Gen VI+
MAX_ACCURACY = 1.0
MIN_DAMAGE = 1  # Minimum damage dealt (prevents 0 damage)

# Damage Formula Constants (Pokémon-inspired)
DAMAGE_STAT_SMOOTHING = 15      # added to atk and def to compress stat ratios toward 1.0
DAMAGE_DIVISOR = 3              # calibrated for CoDEX stat ranges (Pokémon uses 50)
DAMAGE_FLAT_BONUS = 2           # minimum damage floor on hit
DAMAGE_VARIANCE_MIN = 0.85      # random roll lower bound
DAMAGE_VARIANCE_MAX = 1.0       # random roll upper bound (Pokémon: 85-100%)

# 3d8 Resource Economy Reference
# Each alive Core rolls 1d8 per turn; player allocates each roll to Energy or Physical pool.
# Pools accumulate across turns. Move costs are balanced against these income rates.
THREE_D8_MIN = 3
THREE_D8_MAX = 24
THREE_D8_MEAN = 13.5
THREE_D8_PERCENTILES = {10: 7, 25: 10, 50: 13, 75: 17, 90: 19, 95: 21}
EXPECTED_INCOME_PER_POOL = {3: 6.75, 2: 4.5, 1: 2.25}  # cores alive → avg per resource action
