# Generated by Django 6.0.1 on 2026-01-20 03:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("codex", "0006_move_is_signature_alter_move_core_type_identity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                            ("EXTREME", "Extreme"),
                        ],
                        default="EASY",
                        max_length=20,
                    ),
                ),
                ("requirements", models.JSONField(blank=True, default=dict)),
                ("rewards", models.JSONField(blank=True, default=dict)),
                ("enemy_config", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_repeatable", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("zone", models.CharField(blank=True, default="", max_length=60)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "difficulty", "name"],
            },
        ),
        migrations.CreateModel(
            name="Battle",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "battle_type",
                    models.CharField(
                        choices=[
                            ("PVP", "Player vs Player"),
                            ("PVE", "Player vs Environment"),
                            ("MISSION", "Mission"),
                        ],
                        default="PVE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("current_turn", models.PositiveIntegerField(default=0)),
                ("rewards", models.JSONField(blank=True, default=dict)),
                (
                    "operator_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battles_as_operator_1",
                        to="codex.operator",
                    ),
                ),
                (
                    "operator_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battles_as_operator_2",
                        to="codex.operator",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battles_won",
                        to="codex.operator",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battles",
                        to="battle.mission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BattleTeam",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("energy_pool", models.PositiveIntegerField(default=0)),
                ("physical_pool", models.PositiveIntegerField(default=0)),
                (
                    "active_core_index",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="battle.battle",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_teams",
                        to="codex.operator",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BattleCoreState",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ]
                    ),
                ),
                ("current_hp", models.PositiveIntegerField(default=0)),
                ("max_hp", models.PositiveIntegerField(default=0)),
                ("is_knocked_out", models.BooleanField(default=False)),
                (
                    "last_dice_roll",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                ("status_effects", models.JSONField(blank=True, default=list)),
                (
                    "core",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_states",
                        to="codex.core",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="core_states",
                        to="battle.battleteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BattleTurn",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("turn_number", models.PositiveIntegerField()),
                ("state_before", models.JSONField(blank=True, default=dict)),
                ("state_after", models.JSONField(blank=True, default=dict)),
                (
                    "acting_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns_acted",
                        to="battle.battleteam",
                    ),
                ),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="battle.battle",
                    ),
                ),
            ],
            options={
                "ordering": ["turn_number"],
            },
        ),
        migrations.CreateModel(
            name="BattleAction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("MOVE", "Move"),
                            ("SWITCH", "Switch"),
                            ("PASS", "Pass"),
                            ("REACTION", "Reaction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("damage_dealt", models.PositiveIntegerField(default=0)),
                ("accuracy_check", models.BooleanField(blank=True, null=True)),
                ("was_critical", models.BooleanField(default=False)),
                ("energy_cost", models.PositiveIntegerField(default=0)),
                ("physical_cost", models.PositiveIntegerField(default=0)),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battle_actions",
                        to="codex.move",
                    ),
                ),
                (
                    "source_core",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions_as_source",
                        to="battle.battlecorestate",
                    ),
                ),
                (
                    "target_core",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions_as_target",
                        to="battle.battlecorestate",
                    ),
                ),
                (
                    "turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="battle.battleturn",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="DiceRoll",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "roll_value",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ]
                    ),
                ),
                (
                    "allocated_to",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ENERGY", "Energy Pool"),
                            ("PHYSICAL", "Physical Pool"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "core_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dice_rolls",
                        to="battle.battlecorestate",
                    ),
                ),
                (
                    "turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dice_rolls",
                        to="battle.battleturn",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Mail",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mail_type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System"),
                            ("REWARD", "Reward"),
                            ("BATTLE_RESULT", "Battle Result"),
                            ("MISSION_UPDATE", "Mission Update"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                ("attachments", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("is_claimed", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail",
                        to="codex.operator",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mail",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperatorMission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("victories", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("rewards_claimed", models.BooleanField(default=False)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_progress",
                        to="battle.mission",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="codex.operator",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="battleteam",
            constraint=models.UniqueConstraint(
                fields=("battle", "operator"), name="uniq_battle_operator_team"
            ),
        ),
        migrations.AddConstraint(
            model_name="battlecorestate",
            constraint=models.UniqueConstraint(
                fields=("team", "position"), name="uniq_team_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="battlecorestate",
            constraint=models.UniqueConstraint(
                fields=("team", "core"), name="uniq_team_core"
            ),
        ),
        migrations.AddConstraint(
            model_name="battleturn",
            constraint=models.UniqueConstraint(
                fields=("battle", "turn_number", "acting_team"),
                name="uniq_battle_turn_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="operatormission",
            constraint=models.UniqueConstraint(
                fields=("operator", "mission"), name="uniq_operator_mission"
            ),
        ),
    ]
