# Generated by Django 6.0.1 on 2026-01-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mail",
            name="sender_name",
            field=models.CharField(default="System", max_length=100),
        ),
        migrations.AlterField(
            model_name="mail",
            name="mail_type",
            field=models.CharField(
                choices=[
                    ("SYSTEM", "System"),
                    ("REWARD", "Reward"),
                    ("BATTLE_RESULT", "Battle Result"),
                    ("MISSION_UPDATE", "Mission Update"),
                    ("NPC", "NPC Message"),
                    ("OPERATOR", "Operator Message"),
                    ("CORP", "Corporation Message"),
                ],
                default="SYSTEM",
                max_length=20,
            ),
        ),
    ]
