# Generated by Django 6.0.1 on 2026-01-23 03:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battle", "0002_mail_sender_name_alter_mail_mail_type"),
        ("codex", "0006_move_is_signature_alter_move_core_type_identity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NPCOperator",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("call_sign", models.CharField(max_length=120, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("bio", models.TextField(blank=True, default="")),
                (
                    "portrait_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "arena_rank",
                    models.CharField(
                        choices=[
                            ("S", "S"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                        ],
                        default="E",
                        max_length=2,
                    ),
                ),
                ("floor", models.PositiveIntegerField(default=1)),
                (
                    "difficulty_rating",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("core_level_range", models.JSONField(blank=True, default=dict)),
                (
                    "win_mail_subject",
                    models.CharField(default="Victory Acknowledged", max_length=200),
                ),
                ("win_mail_body", models.TextField(blank=True, default="")),
                (
                    "lose_mail_subject",
                    models.CharField(default="Defeat Recorded", max_length=200),
                ),
                ("lose_mail_body", models.TextField(blank=True, default="")),
                ("reward_bits", models.PositiveIntegerField(default=100)),
                ("reward_exp", models.PositiveIntegerField(default=50)),
                ("is_gate_boss", models.BooleanField(default=False)),
                (
                    "unlocks_rank",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["arena_rank", "floor"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("arena_rank", "floor"), name="uniq_arena_rank_floor"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NPCCore",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("core_type", models.CharField(blank=True, default="", max_length=60)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("Common", "Common"),
                            ("Uncommon", "Uncommon"),
                            ("Rare", "Rare"),
                            ("Legendary", "Legendary"),
                            ("Mythic", "Mythic"),
                        ],
                        default="Common",
                        max_length=20,
                    ),
                ),
                ("lvl", models.PositiveIntegerField(default=1)),
                ("image_url", models.CharField(blank=True, default="", max_length=500)),
                (
                    "team_position",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                ("hp", models.PositiveIntegerField(default=100)),
                ("physical", models.PositiveIntegerField(default=10)),
                ("energy", models.PositiveIntegerField(default=10)),
                ("defense", models.PositiveIntegerField(default=10)),
                ("shield", models.PositiveIntegerField(default=10)),
                ("speed", models.PositiveIntegerField(default=10)),
                (
                    "npc_operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cores",
                        to="battle.npcoperator",
                    ),
                ),
            ],
            options={
                "ordering": ["npc_operator", "team_position"],
            },
        ),
        migrations.CreateModel(
            name="OperatorArenaProgress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_rank", models.CharField(default="E", max_length=2)),
                ("defeated_npcs", models.JSONField(blank=True, default=list)),
                ("arena_wins", models.PositiveIntegerField(default=0)),
                ("arena_losses", models.PositiveIntegerField(default=0)),
                ("current_win_streak", models.PositiveIntegerField(default=0)),
                ("best_win_streak", models.PositiveIntegerField(default=0)),
                (
                    "operator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arena_progress",
                        to="codex.operator",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NPCCoreEquippedMove",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slot",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="npc_equipped_by",
                        to="codex.move",
                    ),
                ),
                (
                    "npc_core",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipped_moves",
                        to="battle.npccore",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("npc_core", "slot"), name="uniq_npc_core_slot"
                    ),
                    models.UniqueConstraint(
                        fields=("npc_core", "move"), name="uniq_npc_core_move"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="npccore",
            constraint=models.UniqueConstraint(
                fields=("npc_operator", "team_position"), name="uniq_npc_core_position"
            ),
        ),
    ]
